config/routes.rb
Rails.application.routes.draw do
  #get 'welcome/home'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :comments
  resources :users do 
  	resources :books do
    #users/:id/book_comments
    #book_comments
    #book_comments.html.erb
    end
  end
  get 'users/:id/book_comments' => 'books#book_comments'
  #resources :bookgenres
  get 'genres/most_popular' => 'genres#most_popular'
  resources :genres
  root 'welcome#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

	has_many :bookgenres
	has_many :genres, through: :bookgenres
	accepts_nested_attributes_for :genres

	has_many :comments

	validates :title, presence: true
	validates :author, presence: true

	has_attached_file :epub
	validates_attachment :epub, presence: true,
	  content_type: { content_type: "application/epub+zip" }


	def genres_attributes=(genre_attributes)
	  genre_attributes.values.each do |genre_attribute|
	  	unless genre_attribute['name'].empty?
	    	genre = Genre.find_or_create_by(genre_attribute)
	    	self.genres << genre
	    end
	  end
	end

	def download_link
		epub.url.split('?').first #using paperclip defaults results in downloading a .zip file
	end 

	def self.by_genre(genre)
		joins(:genres).where(genres: {name: genre})
	end
end

app/models/bookgenre.rb
class Bookgenre < ApplicationRecord
	belongs_to :book 
	belongs_to :genre
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :book
	belongs_to :user

	validates :content, presence: true, length: { minimum: 10 }
	validates :user_id, presence: true
	validates :book_id, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :bookgenres
	has_many :books, through: :bookgenres

	validates :name, presence: true

	def self.most_popular
		all.sort_by {|x| x.books.count}.reverse
	end

	def self.alphabetized
		all.sort_by {|x| x.name}
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :books

  has_many :comments

	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookgenres_controller.rb
class BookgenresController < ApplicationController
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = current_user.books
  end

  def show
    if current_user
      @comment = current_user.comments.build
      @comment.book_id = @book.id
    end
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @book}
    end
    #render json: @book
  end

  def new
    @book = current_user.books.build
  end

  def edit
  end

  def create
    @book = current_user.books.build(book_params)
      if @book.save
         redirect_to user_books_path(@book), notice: 'Book was successfully created.' 
       else
         render :new 
      end
  end

  def update
      if @book.update(book_params)
        redirect_to @book, notice: 'Book was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @book.destroy
    redirect_to user_books_url(current_user), notice: 'Book was successfully destroyed.'
  end

  def book_comments
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :author, :epub, :user_id, genre_ids: [], genres_attributes: [:name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def create
    @comment = Comment.create(comment_params)
    render json: @comment, status: 201
      # if @comment.save
      #   redirect_to :back, notice: 'Comment was successfully created.'
      # else
      #   redirect_to :back, alert: "Sorry, your comment couldn't be added. Make sure it is at least 10 characters."
      # end
  end

  def destroy
    @comment.destroy
    redirect_to :back, notice: 'Comment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :book_id, :user_id)
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  def index
    @genres = Genre.alphabetized
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @genres}
    end
  end

  def show
    @books = Book.by_genre(@genre.name)
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @genre}
    end
  end

  def most_popular
    @genres = Genre.most_popular
    render :index
  end

  def new
    @genre = Genre.new
  end

  def edit
  end

  def create
    @genre = Genre.new(genre_params)
      if @genre.save
         redirect_to @genre, notice: 'Genre was successfully created.' 
       else
         render :new 
      end
  end

  def update
      if @genre.update(genre_params)
         redirect_to @genre, notice: 'Genre was successfully updated.'
       else
         render :edit 
       end
  end

  def destroy
    @genre.destroy
    redirect_to genres_url, notice: 'Genre was successfully destroyed.'
  end

  private
    def set_genre
      @genre = Genre.find(params[:id])
    end

    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookgenres_helper.rb
module BookgenresHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
  def genre_links(book)
  	book.genres.map {|genre| link_to genre.name, genre_path(genre)}.join(", ").html_safe
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_for book, url: user_books_path(current_user), html: {multipart: true} do |f| %>

  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :epub %>
    <%= f.file_field :epub %>
  </div>


  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>
  
  <div class="field">
  <%= f.label :genres %>
    <br><%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name %>
    <%= f.fields_for :genres, book.genres.build do |genres_fields| %>
    <br> create a new genre: <%= genres_fields.text_field :name %>
  <% end %>
  </div>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>owner</th>
      <th>filename / download</th>
      <th>title - author</th>
      <th>genre(s)</th>
      <th colspan="3">actions</th>
    </tr>
  </thead>

  <tbody>
    <% books.all.each do |book| %>
      <tr>
        <td><%= book.user.email %></td>
        <td><%= link_to book.epub_file_name, book.download_link %> <span class="glyphicon glyphicon-cloud-download" aria-hidden="true"></span></td>
        <td><%= book.title %> - <%= book.author %></td>
        <td><%= genre_links(book) %></td>
        <td><%= link_to 'more info', user_book_path(book.user, book), class: "moreInfo" %></td>
        <td><%= link_to 'edit', edit_user_book_path(book.user, book) if book.user == current_user %></td>
        <td><%= link_to 'delete', user_book_path(book.user, book), method: :delete, data: { confirm: 'Are you sure?' } if book.user == current_user %></td>
      </tr>
      <tr class="toggleInfo" style="display:none;"><td>ayyyy lmao</td></tr>
    <% end %>
  </tbody>
</table>

app/views/books/book_comments.html.erb
<% current_user.comments.each do |comment| %>
	<p><%= comment.content %></p>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', user_book_path(current_user, @book) %> |
<%= link_to 'Back', user_books_path(current_user) %>

app/views/books/home.html.erb
<div class="well">
  <h2>welcome</h2>
  <p>welcome to the epub library. patrons of the epub library have uploaded <%= Book.count %> books.</p> 
</div>

<%= render partial: "table", locals: {books: Book.all} %>

app/views/books/index.html.erb
<div class="well">
  <h2><%= current_user.email %>'s books</h2>
  <p>this is your book collection.</p> 
</div>

<%= render partial: "table", locals: {books: @books} %>

<br>

<%= link_to 'upload a book', new_user_book_path %>

app/views/books/new.html.erb
<h1>upload a book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', user_books_path(current_user) %>

app/views/books/show.html.erb
<h2><%= @book.title %> - <%= @book.author %></h2>

<table class="table">

	<tr>
		<td>filename/download:</td>
		<td><%= link_to @book.epub_file_name, @book.download_link %></td>
	</tr>
	<tr>
		<td>filesize:</td>
		<td><%= @book.epub_file_size/1000 %> kb</td>
	</tr>
	<tr>
		<td>updated:</td>
		<td><%= @book.epub_updated_at %></td>
	</tr>
	<tr>
		<td>genres:</td>
		<td><%= genre_links(@book) %></td>
	</tr>
</table>


<h3>comments</h3>
<table id="commentsTable" class='table'>
		<tr>
			<td></td>
			<td></td>
		</tr>
	<% @book.comments.each do |comment| %>
		<tr>
			<td><strong><%= comment.user.email %></strong> says: <%= comment.content %></td>
			<td><%= link_to 'delete', comment, method: :delete, data: { confirm: 'Are you sure?' } if comment.user == current_user %></td>
		</tr>
	<% end %>
</table>

<%= render 'comments/form', comment: @comment, book: @book if @comment %>

app/views/comments/_form.html.erb
<h3>add a comment</h3>
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <br><%= f.text_field :content %>
    <%= f.hidden_field :book_id, value: comment.book_id %>
    <%= f.hidden_field :user_id, value: comment.user_id %>
  </div>

<!--   <div class="actions">
    <%= f.submit %>
  </div> -->

  <a href=# id='clickSubmit'>add comment</a>
<% end %>

<script type="text/javascript" charset="utf-8">
  $(function () {

    $(window).keydown(function(event){
      if(event.keyCode == 13) {
        event.preventDefault();
        return false;
      }
    });

    $('#clickSubmit').on('click', function(event) {
      event.preventDefault();
      var values = $('form').serialize();
      var commenting = $.post('/comments', values);
      commenting.success(function(data) {
        console.log(data);
        var comment = new Comment(data);
        if(comment.id==null){
          alert("Your comment failed to validate. Please try again.")
        } else {
          $('#commentsTable tr:last').after(comment.formatComment());
        }
      });
    });
  });
</script>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment, book: @book %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/genres/_form.html.erb
<%= form_for(genre) do |f| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<div class="well">
  <h2>browse by genre</h2>
  <p>here, you can browse the library's collection by genre. there are currently <%= Genre.count %> genres to choose from. <%= link_to 'click here see the most popular genres.', '/genres/most_popular' %> </p> 
</div>

<div style='display: none;' class="genreContainer"></div>
    
<script>
$(function() {
  	$.get("/genres.json")
	  	.success(function(genres) {
	    	$.each(genres, function(key, genreHash){
	    		var genre = new Genre(genreHash); 
	    		$('.genreContainer').append(genre.formatGenre());
	    	});
	    	$('.genreContainer').fadeIn();
	    });
});
</script>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<a href="#" class="nextGenre" data-id="<%=@genre.id%>">next genre</a>

<div id="genreContainer" class="well">
  <h2 id="genreName"></h2>
  <p id="genreBooks"></p>
</div>

<script>
genreShow();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>nadir library</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>



  

  <body >


    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">nadir library</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'all books', root_path %></li>
            <li><%= link_to 'browse by genre', genres_path %></li>
            <li><%= link_to 'my books', user_books_path(current_user) if user_signed_in? %></li>
            <li><%= link_to 'sign up', new_user_registration_path unless user_signed_in? %></li>
            <li><%= link_to 'log in', new_user_session_path unless user_signed_in? %></li>
            <li><%= link_to 'log out', destroy_user_session_path, method: :delete if user_signed_in?%></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

  
  <div class="container">

  
    <% if notice %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
    
    <% if alert  %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>



      <%= yield %>
	</div>
  </body>
</html>

app/views/welcome/home.html.erb
<div class="well">
  <h2>welcome</h2>
  <p>welcome to the nadir library, home of the best .epub format ebooks. there are currently <%= Book.count %> books in the library.</p> 
</div>

<%= render partial: "books/table", locals: {books: Book.all} %>